import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Our App",
	description: "Generated by create next app",
};

export default function Root({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<Nav />
				<main>{children}</main>
				<footer>
					<ul>
						<li>Footer 1</li>
						<li>Footer 1</li>
						<li>Footer 1</li>
					</ul>
				</footer>
			</body>
		</html>
	);
}

// <RootLayout>
//   <About />
// </RootLayout>
