import "./globals.css";
import Nav from "./components/Nav";

export const metadata = {
	title: "Our App",
	description: "Generated by create next app",
};
import ReduxProvider from "./components/ReduxProvider";
export default function Root({ children }) {
	return (
		<html lang="en">
			<body>
				<Nav />
				<ReduxProvider>
					<main>{children}</main>
				</ReduxProvider>
				<footer>
					<ul>
						<li>Footer 1</li>
						<li>Footer 1</li>
						<li>Footer 1</li>
					</ul>
				</footer>
			</body>
		</html>
	);
}

// <RootLayout>
//   <About />
// </RootLayout>
